name: trunkform-ai

concurrency: trunkform-ai

on:
  push:
    branches:
      - trunk
    paths:
      - 'trunkform.ai/**/*'
      - '.github/workflows/trunkform.ai.yml'

jobs:
  ci-then-cd:
    name: ${{ matrix.ENV.environment }}
    defaults:
      run:
        working-directory: ./trunkform.ai
    strategy:
      matrix:
        ENV:
          - environment: ci
            account: 810322435582
          - environment: prod
            account: 245760921574
      max-parallel: 1
    permissions:
    permissions:
      id-token: write # This is required for OIDC authentication with AWS
      contents: read  # This is required for actions/checkout

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '24'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 #v6.0.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::{{ matrix.ENV.account }}:role/github-oidc-provider-trunkform
